### ISSUE TITLE
Node support?

### ISSUE THREAD

**Issue by nicolo-ribaudo** [salesforce/observable-membrane#29]
### Description

When loading this library in node, it throws an error:
```
/home/nicolo/Documenti/dev/babel/babel/packages/babel-traverse/node_modules/observable-membrane/dist/commonjs/observable-membrane.js:349
    const devWindow = window;
                      ^

ReferenceError: window is not defined
    at init (/home/nicolo/Documenti/dev/babel/babel/packages/babel-traverse/node_modules/observable-membrane/dist/commonjs/observable-membrane.js:349:23)
    at Object.<anonymous> (/home/nicolo/Documenti/dev/babel/babel/packages/babel-traverse/node_modules/observable-membrane/dist/commonjs/observable-membrane.js:356:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at _observableMembrane (/home/nicolo/Documenti/dev/babel/babel/packages/babel-traverse/lib/ast-membrane.js:9:39)
```

I can work it around by setting `NODE_ENV=production` so that that file isn't loaded, but I don't think that it should be a requirement.

#### Browsers Affected
node

#### Version
Node: 11
observable-membrane: 0.26.0

**Possible Solution**

Maybe check `typeof window !== undefined` at
https://github.com/salesforce/observable-membrane/blob/2764bb3154899f2323fc2a33b4028362bd4f2fd1/src/reactive-membrane.ts#L15
?

**Comment by caridy** [comment]
@nicolo-ribaudo this is due to the chrome-specific feature that we use to improve proxy inspection in the dev-tools, we have a couple of options here:

1. get rid of it, and instead, apps can use `unwrapProxy` to achieve the same when available.
2. add extra guard for that window reference to make it work on node.

I'm leaning toward 1. @diervo what do you think?

**Comment by pmdartus** [comment]
IMO custom formatter is something that is really useful for developers that are not aware that their objects are wrapped into an observable membrane (https://developer.salesforce.com/blogs/2019/02/debug-your-lightning-web-components.html section custom formatting).

I would advocate adding an extra safeguard to the condition.
